version: '3'

services:

  # rtsptoweb:
  roverr_rtsp_stream:
    restart: always
    image: ghcr.io/deepch/rtsptoweb:latest
    container_name: roverr_rtsp_stream
    volumes:
      #- /teleicu/videos:/app/videos
      - /teleicu/RTSPtoWeb/config.json:/config/config.json
    ports:
      - "8080:8080"
      #- "8081:80"

  # teleicu_middleware
  teleicu_middleware:
    restart: always
    image: ghcr.io/coronasafe/teleicu_middleware/teleicu_middleware:latest
    container_name: teleicu_middleware
    depends_on:
      - roverr_rtsp_stream
    environment:
      - PORT=8090
    ports:
      - "8090:8090"

  # proxies requests to internal services
  reverse-proxy:
    restart: always
    image: ghcr.io/coronasafe/teleicu_nginx/teleicu_nginx:latest
    container_name: reverse-proxy
    depends_on:
      - roverr_rtsp_stream
      - teleicu_middleware
    ports:
      - "8001:8001"

  #watchtower
  watchtower:
    restart: always
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_SCHEDULE=0 * * * * *